name: notification issus Test

on:
  workflow_dispatch:

jobs:
  issues-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run some build step
        run: exit 1 # テストで失敗をシミュレーション

  notify-issus:
    needs: issues-test
    runs-on: ubuntu-latest
    if: failure()
    permissions: # 通知はできていたが書き込みができなかったため追加
      contents: read
      issues: write # Issuesの書き込み権限を付与
    steps:
      - name: Prepare issue content
        run: |
          echo "The workflow ${{ github.workflow }} has failed." > issue-content.md
          echo "Commit: ${{ github.sha }}" >> issue-content.md
          echo "Details: ${{ github.server_url }}/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> issue-content.md

      - name: Create GitHub Issue
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "GitHub Actions Failed: ${{ github.workflow }}"
          content-filepath: ./issue-content.md # ファイルを指定
          labels: |
            automated-issue
